version: '3'
services:
  db:
    image: postgres:14
    restart: always
    env_file:
      - .env
    networks:
      - bird-backend
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
  
  backend:
    image: ghcr.io/bird-exchange/backend:v0.1.0
    restart: always
    env_file:
      - .env
    ports:
      - 8080-5000
    networks:
      - bird-backend
      - bird-frontend
    volumes:
      - ./config:/webapp/config:ro

  frontend:
    image: ghcr.io/bird-exchange/frontend:v0.1.0
    restart: always
    env_file:
      - .env
    ports:
      - 80-5000
    networks:
      - bird-frontend

  minio:
    restart: always
    image: minio/minio:RELEASE.2021-10-10T16-53-30Z
    ports:
      - '9000:9000'
      - '6001:6001'
    command: server /data --console-address ':6001' --address ':9000'
    networks:
      - bird-backend
    environment:
      - MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID}
      - MINIO_ROOT_PASSWORD=${AWS_SECRET_ACCESS_KEY}
      - MINIO_HTTP_TRACE=/dev/stdout
    volumes:
      - ./.data/minio:/data

  networks:
    bird-backend:
    bird-frontend:
